# Generated by Django 2.1.2 on 2018-10-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
