# Generated by Django 2.1.2 on 2018-11-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0002_auto_20181006_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Title',
            new_name='title',
        ),
    ]
