# Generated by Django 2.1.2 on 2018-12-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0003_auto_20181125_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='note',
            name='img',
            field=models.ImageField(default=' ', upload_to='notes-img'),
            preserve_default=False,
        ),
    ]
