# Generated by Django 2.0.3 on 2018-12-05 23:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0004_auto_20181202_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
    ]
